// English for every Latin caption. `real: true` marks wording taken from the Tapestry itself
// (lightly trimmed); the rest is our own dog-Latin.
export const LATIN = {
  'EDWARD REX': { en: 'King Edward', real: true },
  'UBI HAROLD DUX ANGLORUM ET SUI MILITES EQUITANT': { en: 'Where Harold, Duke of the English, and his soldiers ride', real: true },
  'HIC HAROLD ET SUI BIBUNT': { en: 'Here Harold and his men drink' },
  'HIC HAROLD MARE NAVIGAVIT': { en: 'Here Harold sailed the sea', real: true },
  'HAROLDI PEDES': { en: "Harold's feet" },
  'HIC TEMPESTAS': { en: 'Here, a storm' },
  'HIC APPREHENDIT WIDO HAROLDUM': { en: 'Here Guy seizes Harold', real: true },
  'HIC VENIT HAROLD AD WILLELMUM': { en: 'Here Harold comes to William' },
  'UBI UNUS CLERICUS ET ÆLFGYVA': { en: 'Where a cleric and Ælfgyva… (that’s all it says. Really.)', real: true },
  'HIC HAROLD DUX TRAHEBAT EOS DE ARENA': { en: 'Here Duke Harold dragged them out of the sand', real: true },
  'ET CUNAN CLAVES PORREXIT': { en: 'And Conan handed over the keys', real: true },
  'ET VENERUNT AD DOL ET CONAN FUGA VERTIT': { en: 'And they came to Dol, and Conan turned to flight', real: true },
  'HIC PORTATUR CORPUS EADWARDI REGIS AD ECCLESIAM': { en: "Here King Edward's body is carried to the church", real: true },
  'HIC CECIDERUNT SIMUL ANGLI ET FRANCI IN PRELIO': { en: 'Here English and French fell together in battle', real: true },
  'HIC RUSTICUS ARAT': { en: 'Here a farmer ploughs (he is genuinely in the Tapestry border)' },
  'HIC RUSTICUS ADHUC ARAT': { en: 'Here the farmer is still ploughing' },
  'HOMO NORMANNUS': { en: 'The Norman man' },
  ANTE: { en: 'Before' },
  POST: { en: 'After' },
  'HIC MILITES FESTINAVERUNT HESTINGA UT CIBUM RAPERENTUR': { en: 'Here the soldiers hurried to Hastings to seize food', real: true },
  'UNUS SAGITTARIUS ANGLICUS': { en: 'One English archer' },
  'HIC WILLELM DEDIT HAROLDO ARMA': { en: 'Here William gave Harold arms', real: true },
  'UBI HAROLD SACRAMENTUM FECIT WILLELMO DUCI': { en: 'Where Harold swore an oath to Duke William', real: true },
  'HIC HAROLD REDIIT AD ANGLICAM TERRAM': { en: 'Here Harold returned to English land', real: true },
  'HIC PORTATUR CORPUS EADWARDI AD ECCLESIAM': { en: "Here King Edward's body is carried to the church", real: true },
  'HIC EADWARDUS REX IN LECTO ALLOQUITUR FIDELES': { en: 'Here King Edward, in bed, speaks to his faithful', real: true },
  'HIC RESIDET HAROLD REX ANGLORUM': { en: 'Here sits Harold, King of the English', real: true },
  'ISTI MIRANT STELLA': { en: 'These men marvel at the star', real: true },
  HAROLD: { en: 'Harold', real: true },
  'HIC WILLELM IN MARE FRIGIDO': { en: 'Here William, in the cold sea' },
  'HIC SCRIBIT ANGLIA XL': { en: "Here he writes 'England' forty times" },
  'HIC ODO DIGITO MONSTRAT': { en: 'Here Odo points with his finger' },
  'HIC WILLELM DUX IUSSIT NAVES EDIFICARE': { en: 'Here Duke William ordered ships to be built', real: true },
  'HIC CARPENTARII': { en: 'Here, the carpenters' },
  'HIC TRAHUNT NAVES AD MARE': { en: 'Here they drag the ships to the sea', real: true },
  'ISTI PORTANT ARMAS AD NAVES': { en: 'These men carry arms to the ships', real: true },
  'ET HIC GALEAS ET GLADIOS': { en: 'And here, helmets and swords' },
  'ET HIC CARRUM VINO': { en: 'And here, a cart of wine (the Tapestry really does give the wine its own caption)', real: true },
  TUROLD: { en: 'Turold. That’s the whole caption. Nobody knows why.', real: true },
  'STAMFORD BRIDGE': { en: 'Stamford Bridge (not in the Tapestry: Harold’s other battle that autumn)' },
  'EBORACUM AD LUNDONIAM': { en: 'York to London' },
  'HIC WILLELM DUX IN MAGNO NAVIGIO MARE TRANSIVIT': { en: 'Here Duke William crossed the sea in a great ship', real: true },
  'HIC EXEUNT CABALLI DE NAVIBUS': { en: 'Here the horses get out of the ships', real: true },
  'ET HIC CABALLI': { en: 'And here, horses' },
  'HIC COQUITUR CARO': { en: 'Here the meat is cooked', real: true },
  'HIC MINISTRAVERUNT MINISTRI': { en: 'Here the servants served', real: true },
  'HIC EPISCOPUS CIBUM ET POTUM BENEDICIT': { en: 'Here the bishop blesses the food and drink', real: true },
  'ISTE IUSSIT UT FODERETUR CASTELLUM': { en: 'He ordered that a castle be dug', real: true },
  'AT HESTENGACEASTRA': { en: 'at Hastings', real: true },
  'HIC SE VIDENT': { en: 'Here they see each other' },
  'HIC WILLELM DUX ALLOQUITUR SUIS MILITIBUS': { en: 'Here Duke William speaks to his soldiers', real: true },
  'HIC FRANCI PUGNANT': { en: 'Here the French fight', real: true },
  'HIC CECIDERUNT LEWINE ET GYRD FRATRES HAROLDI REGIS': { en: "Here fell Leofwine and Gyrth, King Harold's brothers", real: true },
  'HIC ODO EPS BACULU TENENS CONFORTAT PUEROS': { en: 'Here Bishop Odo, holding a club, encourages the boys', real: true },
  'HIC EST DUX WILELM': { en: 'Here is Duke William', real: true },
  'INFRA: VENDITIO MAGNA': { en: 'Below: the big sale' },
  'HIC HAROLD REX INTERFECTUS EST': { en: 'Here King Harold is killed', real: true },
  'WILLELMUS VICTOR': { en: 'William the victor' },
  'HIC WILLELM': { en: 'Here William… (the rest is lost)' },
  'HIC WILLELM CORON': { en: 'Here William is crown… (never finished)' },
};

export function translate(latin) {
  const t = latin.replace(/\s+/g, ' ').trim();
  if (LATIN[t]) return LATIN[t];
  if (t.startsWith('HIC ')) return { en: 'Here ' + t.slice(4).toLowerCase() };
  return null;
}
