// Generated by tools/build-lines.mjs
export const LINES = {
 "r01_1": {
  "who": "edward",
  "text": "Harold. My dear boy. A small favour. I need you to pop over to Normandy."
 },
 "r01_2": {
  "who": "harold",
  "text": "Normandy."
 },
 "r01_3": {
  "who": "edward",
  "text": "Lovely time of year."
 },
 "r01_4": {
  "who": "harold",
  "text": "What's the message?"
 },
 "r01_5": {
  "who": "edward",
  "text": "Safe travels, Harold."
 },
 "r02_1": {
  "who": "news",
  "text": "Breaking news. The Earl of Wessex has landed in the wrong country. Harold Godwinson, who was sailing to Normandy, has arrived instead in Ponthieu, where he has been immediately arrested. He is reported to be 'fine', and still holding a hawk. More on that as we get it."
 },
 "r02b_1": {
  "who": "guy",
  "text": "Welcome to Ponthieu! You'll love it here. Lovely beach. Lovely dungeon. You're free to leave whenever someone pays me."
 },
 "r02c_1": {
  "who": "harold",
  "text": "Right. Anyone else? No? Just me then. Fine."
 },
 "r02c_2": {
  "who": "william",
  "text": "Love this energy, Harold! Leadership!"
 },
 "r03_1": {
  "who": "odo",
  "text": "Harold Godwinson. Place your hands upon these boxes."
 },
 "r03_2": {
  "who": "harold",
  "text": "What's in the boxes?"
 },
 "r03_3": {
  "who": "odo",
  "text": "Don't worry about the boxes."
 },
 "r03_4": {
  "who": "william",
  "text": "Just a quick promise, bro. Super casual."
 },
 "r03_5": {
  "who": "harold",
  "text": "What am I promising?"
 },
 "r03_6": {
  "who": "william",
  "text": "That you'll support my vision."
 },
 "r03_7": {
  "who": "harold",
  "text": "What's your vision?"
 },
 "r03_8": {
  "who": "william",
  "text": "England."
 },
 "r03_9": {
  "who": "harold",
  "text": "...Right."
 },
 "r03_10": {
  "who": "odo",
  "text": "And he's touched the boxes! Witnessed!"
 },
 "r03_11": {
  "who": "harold",
  "text": "What was in the boxes."
 },
 "r04_1": {
  "who": "news",
  "text": "We can now bring you the final words of King Edward."
 },
 "r04_2": {
  "who": "edward",
  "text": "...the kingdom... to... Har... Har..."
 },
 "r04_3": {
  "who": "news",
  "text": "We'll play that again."
 },
 "r04_4": {
  "who": "edward",
  "text": "...Har..."
 },
 "r04_5": {
  "who": "news",
  "text": "Some are saying 'Harold'. Others are saying 'Harrow', which is not a person. The Duke of Normandy says it sounded like 'William'. It did not sound like William."
 },
 "r05_1": {
  "who": "teller",
  "text": "In the spring of ten sixty-six, a light appeared in the sky. It burned for a week. People stood in the streets and pointed. They had no word for it, except one. Omen."
 },
 "r05_2": {
  "who": "comet",
  "text": "Hello. I'll be back. Not for you."
 },
 "r06_1": {
  "who": "william",
  "text": "Four a.m. Cold plunge. The English Channel. Cold plunges build discipline. Four fifteen. Journalling. Today I wrote 'England' forty times. That's called manifesting. Five a.m. Council meeting. My brother Odo points at things. That's his whole role. He's very good at it."
 },
 "r06_2": {
  "who": "william",
  "text": "People ask me, 'William, why do you want England?' And I say... 'Why don't you?'"
 },
 "r07_1": {
  "who": "ad",
  "text": "Planning an invasion? You'll need boats. Norman Nautical! We fell the trees. We shape the planks. We haul them to the sea. Seven hundred ships. One summer. No questions asked."
 },
 "r07_2": {
  "who": "ad",
  "text": "Norman Nautical is not responsible for weather, horses, Saxons, or the long-term consequences of conquest. Ships may contain horses."
 },
 "r08_1": {
  "who": "william",
  "text": "Tonight, seven hundred ships cross the sea. Tomorrow, England."
 },
 "r08_2": {
  "who": "william",
  "text": "Not now, Gerald."
 },
 "r09_1": {
  "who": "cook",
  "text": "G'day, Normans! Welcome back to Invasion Barbie! Today we're doing a classic. Meat, on a stick, on a fire. Simple. Rustic. Conquest-ready. Bit of chicken. Bit of mystery meat. Don't ask."
 },
 "r09_2": {
  "who": "cook",
  "text": "And that's the bell! Grub's up!"
 },
 "r09_3": {
  "who": "odo",
  "text": "WAIT. I HAVEN'T BLESSED IT."
 },
 "r09_4": {
  "who": "cook",
  "text": "Aw, Bish."
 },
 "r10_1": {
  "who": "ad",
  "text": "Just arrived in a hostile country? You need a castle. Fast. Introducing: the Motte-in-a-Box! Pre-cut timber. One mound. Some assembly required."
 },
 "r10_2": {
  "who": "william",
  "text": "We put it up in a day."
 },
 "r10_3": {
  "who": "ad",
  "text": "Two men may hit each other with shovels during construction. That's normal. Motte-in-a-Box. Conquer with confidence!"
 },
 "r11_1": {
  "who": "william",
  "text": "I want you to close your eyes. Actually, don't. There's a battle."
 },
 "r11_2": {
  "who": "william",
  "text": "I want you to think about what you want. Not what the English want. Not what God wants. Okay, partly what God wants. Odo, nod."
 },
 "r11_3": {
  "who": "william",
  "text": "Today isn't about winning. It is entirely about winning. Charge!"
 },
 "r12_1": {
  "who": "news",
  "text": "And we're live from Senlac Hill, where the English shield wall is holding, it is holding, the Normans charging up the hill for the third time this morning! Harold's men are not moving. They are a wall. They are a very tired wall."
 },
 "r12_2": {
  "who": "news",
  "text": "And the Normans are... retreating? Are they retreating? The English are going after them. Oh no. They're going after them. Don't go after them. They've gone after them."
 },
 "r13_1": {
  "who": "odo",
  "text": "Bishops do not carry swords! We do not shed blood!"
 },
 "r13_2": {
  "who": "odo",
  "text": "This is a club. It's very different."
 },
 "r13_3": {
  "who": "odo",
  "text": "It's pastoral."
 },
 "r13_4": {
  "who": "odo",
  "text": "Courage, boys! God is watching! So am I."
 },
 "r14_1": {
  "who": "soldier",
  "text": "The Duke is dead! William is dead!"
 },
 "r14_2": {
  "who": "william",
  "text": "I'M NOT DEAD! LOOK AT MY FACE. THIS IS MY FACE."
 },
 "r14_3": {
  "who": "eustace",
  "text": "That's him! That's the Duke!"
 },
 "r14_4": {
  "who": "william",
  "text": "Note to self: helmet with a face hole."
 },
 "r15_1": {
  "who": "teller",
  "text": "Late in the afternoon, the shield wall broke. Somewhere in the scrum, Harold, King of England for nine months and nine days, fell."
 },
 "r15_2": {
  "who": "teller",
  "text": "The Tapestry shows a man with an arrow at his eye, and a man being cut down by a horseman. It writes his name above them both. It doesn't say which one was him. Perhaps that's the kindest thing it does."
 },
 "r16_1": {
  "who": "news",
  "text": "And finally. We've lost the ending. The final part of the Bayeux Tapestry, thought to show William's coronation on Christmas Day, is missing. It may have been cut off. It may have worn away. It may never have been finished. Nobody knows how it ends. We're told that's your problem now."
 },
 "r17_1": {
  "who": "teller",
  "text": "Seventy metres of linen. Nine hundred and sixty years. And here you are. Still scrolling. Go on, then. Finish it."
 },
 "r18_1": {
  "who": "turold",
  "text": "Hiya. Turold. That's me, up there, in the actual stitching."
 },
 "r18_2": {
  "who": "turold",
  "text": "Do I do anything important? I hold horses. Am I a king? No. A bishop? No."
 },
 "r18_3": {
  "who": "turold",
  "text": "And yet. Seventy metres of tapestry, and they spelled my name right."
 },
 "r18_4": {
  "who": "turold",
  "text": "I'M IN THE BACKGROUND! HIYA!"
 },
 "r19_1": {
  "who": "aelfgyva",
  "text": "You'll never know."
 },
 "r20_1": {
  "who": "conan",
  "text": "Right. Normans at the front door. Not a problem. I've got a rope."
 },
 "r20_2": {
  "who": "conan",
  "text": "This is fine. Totally planned. Very dignified. Very, very dignified."
 },
 "r20_3": {
  "who": "conan",
  "text": "And that, lads, is what we call a French exit."
 },
 "r20_4": {
  "who": "william",
  "text": "Conan? Conan? We had a meeting booked."
 },
 "r21_1": {
  "who": "news",
  "text": "A correction. Earlier, we showed you the funeral of King Edward. We then showed you King Edward, in bed, very much talking."
 },
 "r21_2": {
  "who": "news",
  "text": "The Tapestry has put these the wrong way round. We'd like to make clear that the King was not, at the time of his funeral, alive."
 },
 "r21_3": {
  "who": "edward",
  "text": "I was a bit alive."
 },
 "r21_4": {
  "who": "news",
  "text": "He was a bit alive."
 },
 "r22_1": {
  "who": "ghost",
  "text": "Boats... Lots... of... boats..."
 },
 "r23_1": {
  "who": "news",
  "text": "Oh. Oh no. And the horses have found the ditch."
 },
 "r23_2": {
  "who": "news",
  "text": "That's a ten for artistic impression. And a zero for everything else."
 },
 "r24_1": {
  "who": "archer",
  "text": "Hiya. I'm the English archery division. All of it."
 },
 "r24_2": {
  "who": "archer",
  "text": "The Normans have brought thirty-four archers. Plus one bloke on a horse with a bow. Showing off."
 },
 "r24_3": {
  "who": "archer",
  "text": "Doesn't matter. I've got one bow, eleven arrows, and a can-do attitude."
 },
 "r24_4": {
  "who": "archer",
  "text": "I'd like to request backup."
 },
 "r24_5": {
  "who": "harold",
  "text": "There is no backup. You are the backup."
 },
 "r25_1": {
  "who": "farmer",
  "text": "Morning. Bit of harrowing today. Then, if there's time, a bit more harrowing."
 },
 "r25_2": {
  "who": "farmer",
  "text": "Still farming."
 },
 "r25_3": {
  "who": "farmer",
  "text": "One fewer sheep, mind."
 },
 "r26_1": {
  "who": "ad",
  "text": "Tired of looking English? Introducing: The Norman! Short at the front. And at the back? Nothing at the back."
 },
 "r26_2": {
  "who": "ad",
  "text": "Moustache removal included. Neck may get cold. Not suitable for Saxons unless you are planning to change sides."
 },
 "r27_1": {
  "who": "cook",
  "text": "Farm to fork, Normans! Today's sheep is locally sourced. Very locally. From that bloke's field."
 },
 "r27_2": {
  "who": "farmer",
  "text": "Oi. That's my sheep, that is."
 }
};
