// Writes app/js/lines.js: each voice clip's speaker and its subtitle (stage directions removed).
import { writeFileSync } from 'node:fs';
import { LINES } from './voice-lines.mjs';
const out = {};
for (const [id, who, text] of LINES) out[id] = { who, text: text.replace(/\[[^\]]*\]\s*/g, '').replace(/\s+/g, ' ').trim() };
writeFileSync(new URL('../app/js/lines.js', import.meta.url), `// Generated by tools/build-lines.mjs\nexport const LINES = ${JSON.stringify(out, null, 1)};\n`);
console.log(Object.keys(out).length, 'lines');
